name: gpt-qna-matome
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - pip
  - python=3.11
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - asyncio==3.4.3
      - blinker==1.9.0
      - certifi==2024.8.30
      - click==8.1.7
      - distro==1.9.0
      - flask==3.1.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jiter==0.7.1
      - markupsafe==3.0.2
      - openai==1.54.4
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dotenv==1.0.1
      - slack-sdk==3.33.3
      - sniffio==1.3.1
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - ujson==5.10.0
      - werkzeug==3.1.3
